M48
; DRILL file {KiCad 8.0.4} date 2024-09-14T16:47:45+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-14T16:47:45+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X248.12Y-83.42
X248.12Y-87.42
T2
X241.31Y-96.525
X241.31Y-107.955
M30
